# Generated by Django 5.1.3 on 2024-12-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'notes', 'verbose_name_plural': 'notes'},
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
